### ISSUE TITLE
关于使用2.3.11的问题

### ISSUE THREAD

**Issue by Wrecking-Ball** [cannanlly/gogotester#1]
@cannanlly 
你好，我想反馈两个关于2.3.11的问题，虽然不影响使用，但是我还是想反馈一下。

1.打开软件，加载ip，默认的线程是100，但是开始随机测试之后，线程总是20，30左右。
   必须手动修改线程数，比如90几，100。随机测试时线程数才会到达100.

2.导出ip为json格式，最后一个ip后面有一个逗号，能不能去掉。

**Comment by cannanlly** [comment]
感想反馈！
1：窗口上的显示数值改回20了，手动修改会改变线程数，C#比较神奇，更改dialog上的控件值居然无效果，还是手动改一下吧。
2：结尾的逗号已去掉
